version: '3.3'

services:
  ui:
    container_name: ui
    image: ui:dev
    build:
      context: ./vue-ui
      dockerfile: Dockerfile
    ports:
      - mode: host
        target: 8080
        published: 8080
        protocol: tcp
    volumes:
      - ./vue-ui:/app
      - type: volume
        target: /app/node_modules
    depends_on:
      - core-api
    networks:
      - core-docker

  core-api:
    container_name: core-api
    image: core-api:dev
    build:
      context: ./core-api
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:61396
      - SECRET_KEY=08826DEF-5B39-4158-B51A-0E78133E08FC
    depends_on:
      - core-auth
      - core-logging
    ports:
      - mode: host
        target: 61396
        published: 61396
        protocol: tcp
    networks:
      - core-docker

  core-logging:
    container_name: core-logging
    image: core-logging:dev
    build:
      context: ./core-logging
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:1969
    volumes:
      - ./logs:/logs
    ports:
      - mode: host
        target: 1969
        published: 1969
        protocol: tcp
    networks:
      - core-docker

  core-auth:
    container_name: core-auth
    image: core-auth:dev
    build:
      context: ./core-auth
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:53180
      - SECRET_KEY=08826DEF-5B39-4158-B51A-0E78133E08FC
    depends_on:
      - core-logging
    volumes:
      - ./logs:/logs
    ports:
      - mode: host
        target: 53180
        published: 53180
        protocol: tcp
    networks:
      - core-docker

networks:
  core-docker:
